#
# Makefile : Builds wxWindows samples for Unix.
#

SAMPLES_SUBDIRS=animate artprov aui calendar caret clipboard collpane combo config console controls dataview debugrpt dialogs dialup display dnd docview dragimag drawing erase event except exec font fswatcher grid help htlbox html html/about html/help html/helpview html/printing html/test html/virtual html/widget html/zip image internat ipc joytest keyboard layout listctrl mdi menu minimal notebook popup printing propgrid render ribbon richtext sashtest scroll shaped sockets sound splash splitter statbar stc svg taborder taskbar text thread toolbar treectrl treelist typetest uiaction validate vscroll widgets wizard wrapsizer xrc 

all:
	@for d in $(SAMPLES_SUBDIRS); do (cd $$d && $(MAKE)); done

clean:
	@for d in $(SAMPLES_SUBDIRS); do (cd $$d && $(MAKE) clean); done
